"""Add missing worker and complaint fields

Revision ID: 6f7148aa92cf
Revises: 00b67ca32784
Create Date: 2026-07-22 20:54:25.102905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7148aa92cf'
down_revision: Union[str, Sequence[str], None] = '00b67ca32784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Workers table already exists in DB but not in migrations history clearly or was created manually.
    # However, since alembic upgrade failed with "table workers already exists", we should check if it needs columns.
    # From PRAGMA table_info(workers), it seems to have all expected columns.

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('before_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('after_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('assigned_worker_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_complaints_assigned_worker_id_workers', 'workers', ['assigned_worker_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_constraint('fk_complaints_assigned_worker_id_workers', type_='foreignkey')
        batch_op.drop_column('assigned_at')
        batch_op.drop_column('assigned_worker_id')
        batch_op.drop_column('after_image')
        batch_op.drop_column('before_image')

    # ### end Alembic commands ###
