"""add_complaint_photo_fields

Revision ID: 9ca81db4fb7e
Revises: 
Create Date: 2026-07-14 09:22:34.934645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca81db4fb7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_workers_email'), ['email'], unique=True)
        batch_op.create_unique_constraint(batch_op.f('uq_workers_user_id'), ['user_id'])
        batch_op.create_foreign_key(batch_op.f('fk_workers_current_job_id_complaints'), 'complaints', ['current_job_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_workers_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('current_task')
        batch_op.drop_column('sos')
        batch_op.drop_column('lat')
        batch_op.drop_column('battery')
        batch_op.drop_column('progress')
        batch_op.drop_column('lng')

    # --- Manually added: complaint photo fields ---
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('before_photo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('after_photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # --- Manually added: complaint photo fields ---
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_column('after_photo_url')
        batch_op.drop_column('before_photo_url')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lng', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('battery', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('sos', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('current_task', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_workers_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_workers_current_job_id_complaints'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_workers_user_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_workers_email'))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
