class AppStrings {
  static Map<String, Map<String, String>> values = {
    'en': {
      'app_name': 'SwachhAI',
      'welcome_back': 'Welcome back,',
      'citizen_login': 'Citizen Login',
      'crew_portal': 'Crew Portal',
      'authorized_only': 'Authorized Access Only',
      'email': 'Email',
      'worker_id': 'Worker ID',
      'password': 'Password',
      'login': 'LOGIN',
      'register': 'REGISTER',
      'no_account': "Don't have an account? ",
      'create_account': 'Create Account',
      'full_name': 'Full Name',
      'phone': 'Phone Number',
      'confirm_password': 'Confirm Password',
      'home': 'Home',
      'reports': 'Reports',
      'profile': 'Profile',
      'hello': 'Hello',
      'raise_complaint': 'Raise Complaint',
      'live_stats': 'Live Statistics',
      'total_reports': 'Total Reports',
      'pending_action': 'Pending Action',
      'in_progress': 'In Progress',
      'resolved': 'Resolved',
      'recent_reports': 'Recent Reports',
      'view_all': 'View All',
      'change_location': 'Change Location',
      'current_location': 'CURRENT LOCATION',
      'on_duty': 'ON DUTY',
      'off_duty': 'OFF DUTY',
      'assigned': 'Assigned',
      'queue': 'Queue',
      'start_nav': 'START NAVIGATION',
      'complete_task': 'MARK AS COMPLETED',
      'upload_after': 'Upload After Photo',
      'language': 'Language',
      'logout': 'LOGOUT',
      'edit_profile': 'Edit Profile',
      'about': 'About SwachhAI',
      'privacy': 'Privacy Policy',
      'help': 'Help & Support',
      'feedback': 'Send Feedback',
      'contact': 'Contact Us',
      'faq': 'FAQs',
      'call_support': 'Call Support',
      'email_support': 'Email Support',
      'report_issue': 'Report an Issue',
      'terms': 'Terms & Conditions',
      'how_help': 'How can we help?',
      'find_answers': 'Find answers or talk to our team.',
      'crew_dashboard': 'Crew Dashboard',
      'today_progress': 'Today\'s Progress',
      'tasks_completed': 'Tasks Completed',
      'quick_access': 'Quick Access',
      'map_preview': 'Route Preview',
      'start': 'START',
      'exit': 'EXIT',
      'navigating': 'Navigating...',
      'distance': 'Distance',
      'eta': 'ETA',
      'walking': 'Walking',
      'two_wheeler': 'Two Wheeler',
      'four_wheeler': 'Four Wheeler',
      'nav_start_msg': 'Navigation started. Head north.',
      'nav_straight': 'Continue straight for 400m',
      'nav_dest': 'You have reached your destination',
      'sos': 'SOS',
      'sos_confirm': 'Are you sure you want to trigger an emergency alert?',
      'sos_alert_sent': 'Emergency alert has been sent.',
      'sos_loc_shared': 'Your current location has been shared with the administrator.',
      'new_task_msg': 'A new cleaning task has been assigned to you.',
      'starting_nav_msg': 'Starting navigation guidance.',
      'task_completed_msg': 'Task marked as completed. Well done.',
      'route_recalculated': 'Route recalculated.',
    },
    'ta': {
      'app_name': 'ஸ்வச்AI',
      'welcome_back': 'மீண்டும் வருக,',
      'citizen_login': 'குடிமக்கள் உள்நுழைவு',
      'crew_portal': 'பணியாளர் தளம்',
      'authorized_only': 'அங்கீகரிக்கப்பட்ட அணுகல் மட்டும்',
      'email': 'மின்னஞ்சல்',
      'worker_id': 'பணியாளர் ஐடி',
      'password': 'கடவுச்சொல்',
      'login': 'உள்நுழைக',
      'register': 'பதிவு செய்க',
      'no_account': "கணக்கு இல்லையா? ",
      'create_account': 'கணக்கை உருவாக்கு',
      'full_name': 'முழு பெயர்',
      'phone': 'தொலைபேசி எண்',
      'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்து',
      'home': 'முகப்பு',
      'reports': 'புகார்கள்',
      'profile': 'சுயவிவரம்',
      'hello': 'வணக்கம்',
      'raise_complaint': 'புகார் செய்க',
      'live_stats': 'நேரடி புள்ளிவிவரங்கள்',
      'total_reports': 'மொத்த புகார்கள்',
      'pending_action': 'நிலுவையில் உள்ளது',
      'in_progress': 'செயலில் உள்ளது',
      'resolved': 'தீர்வு காணப்பட்டது',
      'recent_reports': 'சமீபத்திய புகார்கள்',
      'view_all': 'அனைத்தையும் பார்',
      'change_location': 'இருப்பிடத்தை மாற்று',
      'current_location': 'தற்போதைய இருப்பிடம்',
      'on_duty': 'பணியில்',
      'off_duty': 'பணியில் இல்லை',
      'assigned': 'ஒதுக்கப்பட்டது',
      'queue': 'வரிசை',
      'start_nav': 'வழிகாட்டலைத் தொடங்கு',
      'complete_task': 'பணியை முடி',
      'upload_after': 'சுத்தம் செய்த பின் புகைப்படம்',
      'language': 'மொழி',
      'logout': 'வெளியேறு',
      'edit_profile': 'சுயவிவரத்தைத் திருத்து',
      'about': 'ஸ்வச்AI பற்றி',
      'privacy': 'தனியுரிமைக் கொள்கை',
      'help': 'உதவி மற்றும் ஆதரவு',
      'feedback': 'கருத்துத் தெரிவிக்க',
      'contact': 'தொடர்பு கொள்ள',
      'faq': 'கேள்வி பதில்கள்',
      'call_support': 'அழைப்பு ஆதரவு',
      'email_support': 'மின்னஞ்சல் ஆதரவு',
      'report_issue': 'பிரச்சினையைப் புகாரளிக்கவும்',
      'terms': 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
      'how_help': 'நாங்கள் உங்களுக்கு எப்படி உதவ முடியும்?',
      'find_answers': 'பதில்களைக் கண்டறியவும் அல்லது எங்களுடன் பேசவும்.',
      'crew_dashboard': 'பணியாளர் டாஷ்போர்டு',
      'today_progress': 'இன்றைய முன்னேற்றம்',
      'tasks_completed': 'பணிகள் முடிந்தது',
      'quick_access': 'விரைவான அணுகல்',
      'map_preview': 'பாதை முன்னோட்டம்',
      'start': 'தொடங்கு',
      'exit': 'வெளியேறு',
      'navigating': 'வழிகாட்டுகிறது...',
      'distance': 'தூரம்',
      'eta': 'நேரம்',
      'walking': 'நடந்து செல்லுதல்',
      'two_wheeler': 'இருசக்கர வாகனம்',
      'four_wheeler': 'நான்கு சக்கர வாகனம்',
      'nav_start_msg': 'வழிகாட்டல் தொடங்கியது. வடக்கு நோக்கி செல்லுங்கள்.',
      'nav_straight': '400 மீட்டருக்கு நேராக செல்லவும்',
      'nav_dest': 'உங்கள் இலக்கை வந்தடைந்துவிட்டீர்கள்',
      'sos': 'அவசர உதவி',
      'sos_confirm': 'அவசர உதவி எச்சரிக்கையைத் தூண்ட விரும்புகிறீர்களா?',
      'sos_alert_sent': 'அவசர உதவி கோரிக்கை அனுப்பப்பட்டுள்ளது.',
      'sos_loc_shared': 'உங்கள் இருப்பிடம் நிர்வாகத்திற்கு அனுப்பப்பட்டுள்ளது.',
      'new_task_msg': 'உங்களுக்கு ஒரு புதிய தூய்மை பணியை ஒதுக்கியுள்ளோம்.',
      'starting_nav_msg': 'வழிகாட்டுதலை தொடங்குகிறோம்.',
      'task_completed_msg': 'பணி முடிக்கப்பட்டதாகக் குறிக்கப்பட்டது. நன்று.',
      'route_recalculated': 'பாதை மாற்றியமைக்கப்பட்டது.',
    }
  };

  static String get(String key, String locale) {
    return values[locale]?[key] ?? key;
  }
}
